name: Update Coverage Badge

on:
  push:
    branches:
      - main

jobs:
  update_coverage_badge:
    name: Update Coverage Badge
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:14-3.2-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: tekdb
        ports:
          - 5432:5432
    env:
      SQL_ENGINE: django.contrib.gis.db.backends.postgis
      SQL_DATABASE: tekdb
      SQL_USER: postgres
      SQL_PASSWORD: postgres
      SQL_HOST: localhost
      SQL_PORT: 5432
      DEBUG: 1
      SECRET_KEY: ${{ secrets.POSTGRES_SECRET_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gdal-bin -y

      - name: Install Python dependencies
        run: |
          python -m pip install -r TEKDB/requirements.txt

      - name: Run Coverage Report
        run: |
          cd TEKDB && coverage run manage.py test
          coverage json
      
      - name: Access Coverage Stat
        run: |
          export TOTAL=$(python -c "import json;print(json.load(open('TEKDB/coverage.json'))['totals']['percent_covered_display'])")
          echo "total=$TOTAL" >> $GITHUB_ENV
          echo "### Total coverage: ${TOTAL}%" >> $GITHUB_STEP_SUMMARY

      - name: Make Coverage Badge
        uses: Schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: ${{ secrets.GIST_ID }}
          filename: coverage-badge.json
          label: Coverage
          message: ${{ env.total }}%
          minColorRange: 50
          maxColorRange: 90
          valColorRange: ${{ env.total }}